// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: protoschemas/mymessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageKind int32

const (
	MessageKind_CLIENT_NOT_FOUND MessageKind = 0  // server -> master
	MessageKind_LOGIN_GET        MessageKind = 1  // server->
	MessageKind_LOGIN_RESP       MessageKind = 2  // ->server
	MessageKind_CLIENTS_GET      MessageKind = 3  // master->
	MessageKind_CLIENTS_RESP     MessageKind = 4  // ->master
	MessageKind_SHELL_OPEN       MessageKind = 5  // master->
	MessageKind_SHELL_OPEN_RES   MessageKind = 6  // client->master
	MessageKind_SHELL_WRITE      MessageKind = 7  // master->
	MessageKind_SHELL_CLOSE      MessageKind = 8  // master->
	MessageKind_SHELL_RESP       MessageKind = 9  // client->master
	MessageKind_DOWN_START       MessageKind = 10 // master->
	MessageKind_UP_START         MessageKind = 11 // master->
	MessageKind_FILE_CHUNK       MessageKind = 12 // master,client->
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0:  "CLIENT_NOT_FOUND",
		1:  "LOGIN_GET",
		2:  "LOGIN_RESP",
		3:  "CLIENTS_GET",
		4:  "CLIENTS_RESP",
		5:  "SHELL_OPEN",
		6:  "SHELL_OPEN_RES",
		7:  "SHELL_WRITE",
		8:  "SHELL_CLOSE",
		9:  "SHELL_RESP",
		10: "DOWN_START",
		11: "UP_START",
		12: "FILE_CHUNK",
	}
	MessageKind_value = map[string]int32{
		"CLIENT_NOT_FOUND": 0,
		"LOGIN_GET":        1,
		"LOGIN_RESP":       2,
		"CLIENTS_GET":      3,
		"CLIENTS_RESP":     4,
		"SHELL_OPEN":       5,
		"SHELL_OPEN_RES":   6,
		"SHELL_WRITE":      7,
		"SHELL_CLOSE":      8,
		"SHELL_RESP":       9,
		"DOWN_START":       10,
		"UP_START":         11,
		"FILE_CHUNK":       12,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protoschemas_mymessage_proto_enumTypes[0].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_protoschemas_mymessage_proto_enumTypes[0]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_CLIENT Role = 0
	Role_MASTER Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "CLIENT",
		1: "MASTER",
	}
	Role_value = map[string]int32{
		"CLIENT": 0,
		"MASTER": 1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_protoschemas_mymessage_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_protoschemas_mymessage_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{1}
}

type Result int32

const (
	Result_OK    Result = 0
	Result_ERROR Result = 1
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Result_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_protoschemas_mymessage_proto_enumTypes[2].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_protoschemas_mymessage_proto_enumTypes[2]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{2}
}

type EmptyBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyBody) Reset() {
	*x = EmptyBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyBody) ProtoMessage() {}

func (x *EmptyBody) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyBody.ProtoReflect.Descriptor instead.
func (*EmptyBody) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{0}
}

type SysInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uname string `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
}

func (x *SysInfo) Reset() {
	*x = SysInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfo) ProtoMessage() {}

func (x *SysInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfo.ProtoReflect.Descriptor instead.
func (*SysInfo) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{1}
}

func (x *SysInfo) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role Role     `protobuf:"varint,1,opt,name=role,proto3,enum=mymessage.Role" json:"role,omitempty"`
	Info *SysInfo `protobuf:"bytes,2,opt,name=info,proto3,oneof" json:"info,omitempty"` // for clients
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{2}
}

func (x *Login) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_CLIENT
}

func (x *Login) GetInfo() *SysInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ClientList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ClientList_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ClientList) Reset() {
	*x = ClientList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientList) ProtoMessage() {}

func (x *ClientList) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientList.ProtoReflect.Descriptor instead.
func (*ClientList) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{3}
}

func (x *ClientList) GetEntries() []*ClientList_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// file transfer header
type FTHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // either dst or src
	Id   uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`    // unique allocated id
}

func (x *FTHeader) Reset() {
	*x = FTHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FTHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FTHeader) ProtoMessage() {}

func (x *FTHeader) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FTHeader.ProtoReflect.Descriptor instead.
func (*FTHeader) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{4}
}

func (x *FTHeader) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FTHeader) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Last bool   `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{5}
}

func (x *FileChunk) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     MessageKind `protobuf:"varint,1,opt,name=kind,proto3,enum=mymessage.MessageKind" json:"kind,omitempty"`
	ClientId *uint64     `protobuf:"varint,2,opt,name=clientId,proto3,oneof" json:"clientId,omitempty"`
	// Types that are assignable to Body:
	//
	//	*Message_Empty
	//	*Message_Login
	//	*Message_Clients
	//	*Message_TextContent
	//	*Message_Res
	//	*Message_Ftheader
	//	*Message_FileChunk
	Body isMessage_Body `protobuf_oneof:"body"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_CLIENT_NOT_FOUND
}

func (x *Message) GetClientId() uint64 {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return 0
}

func (m *Message) GetBody() isMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Message) GetEmpty() *EmptyBody {
	if x, ok := x.GetBody().(*Message_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *Message) GetLogin() *Login {
	if x, ok := x.GetBody().(*Message_Login); ok {
		return x.Login
	}
	return nil
}

func (x *Message) GetClients() *ClientList {
	if x, ok := x.GetBody().(*Message_Clients); ok {
		return x.Clients
	}
	return nil
}

func (x *Message) GetTextContent() string {
	if x, ok := x.GetBody().(*Message_TextContent); ok {
		return x.TextContent
	}
	return ""
}

func (x *Message) GetRes() Result {
	if x, ok := x.GetBody().(*Message_Res); ok {
		return x.Res
	}
	return Result_OK
}

func (x *Message) GetFtheader() *FTHeader {
	if x, ok := x.GetBody().(*Message_Ftheader); ok {
		return x.Ftheader
	}
	return nil
}

func (x *Message) GetFileChunk() *FileChunk {
	if x, ok := x.GetBody().(*Message_FileChunk); ok {
		return x.FileChunk
	}
	return nil
}

type isMessage_Body interface {
	isMessage_Body()
}

type Message_Empty struct {
	Empty *EmptyBody `protobuf:"bytes,3,opt,name=empty,proto3,oneof"`
}

type Message_Login struct {
	Login *Login `protobuf:"bytes,4,opt,name=login,proto3,oneof"`
}

type Message_Clients struct {
	// server->master
	Clients *ClientList `protobuf:"bytes,5,opt,name=clients,proto3,oneof"`
}

type Message_TextContent struct {
	// e.g. shell stdin/stdout
	TextContent string `protobuf:"bytes,6,opt,name=textContent,proto3,oneof"`
}

type Message_Res struct {
	Res Result `protobuf:"varint,7,opt,name=res,proto3,enum=mymessage.Result,oneof"`
}

type Message_Ftheader struct {
	Ftheader *FTHeader `protobuf:"bytes,8,opt,name=ftheader,proto3,oneof"`
}

type Message_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,9,opt,name=fileChunk,proto3,oneof"`
}

func (*Message_Empty) isMessage_Body() {}

func (*Message_Login) isMessage_Body() {}

func (*Message_Clients) isMessage_Body() {}

func (*Message_TextContent) isMessage_Body() {}

func (*Message_Res) isMessage_Body() {}

func (*Message_Ftheader) isMessage_Body() {}

func (*Message_FileChunk) isMessage_Body() {}

type ClientList_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip        string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Uname     string `protobuf:"bytes,3,opt,name=uname,proto3" json:"uname,omitempty"`
	OnlineDur int64  `protobuf:"varint,4,opt,name=onlineDur,proto3" json:"onlineDur,omitempty"`
}

func (x *ClientList_Entry) Reset() {
	*x = ClientList_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoschemas_mymessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientList_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientList_Entry) ProtoMessage() {}

func (x *ClientList_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_protoschemas_mymessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientList_Entry.ProtoReflect.Descriptor instead.
func (*ClientList_Entry) Descriptor() ([]byte, []int) {
	return file_protoschemas_mymessage_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ClientList_Entry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientList_Entry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClientList_Entry) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *ClientList_Entry) GetOnlineDur() int64 {
	if x != nil {
		return x.OnlineDur
	}
	return 0
}

var File_protoschemas_mymessage_proto protoreflect.FileDescriptor

var file_protoschemas_mymessage_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f, 0x6d,
	0x79, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x6d, 0x79, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x1f, 0x0a, 0x07, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x23, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x6d, 0x79, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x79, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x88,
	0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x0a,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x79,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x1a, 0x5b, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x75, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x75, 0x72, 0x22, 0x2e,
	0x0a, 0x08, 0x46, 0x54, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43,
	0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xaa, 0x03, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x6d, 0x79, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x05,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x79,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x6f, 0x64,
	0x79, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x79, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x79, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b,
	0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x72,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x79, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x03, 0x72,
	0x65, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x66, 0x74, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x79, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x46, 0x54, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x66, 0x74, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x79, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00,
	0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x2a, 0xe9, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x14, 0x0a, 0x10, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46,
	0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f,
	0x47, 0x45, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52,
	0x45, 0x53, 0x50, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x53,
	0x5f, 0x47, 0x45, 0x54, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54,
	0x53, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x48, 0x45, 0x4c,
	0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x48, 0x45, 0x4c,
	0x4c, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x48, 0x45, 0x4c, 0x4c, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x07, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x48, 0x45, 0x4c, 0x4c, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x08, 0x12, 0x0e,
	0x0a, 0x0a, 0x53, 0x48, 0x45, 0x4c, 0x4c, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x09, 0x12, 0x0e,
	0x0a, 0x0a, 0x44, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x0a, 0x12, 0x0c,
	0x0a, 0x08, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x0b, 0x12, 0x0e, 0x0a, 0x0a,
	0x46, 0x49, 0x4c, 0x45, 0x5f, 0x43, 0x48, 0x55, 0x4e, 0x4b, 0x10, 0x0c, 0x2a, 0x1e, 0x0a, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01, 0x2a, 0x1b, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoschemas_mymessage_proto_rawDescOnce sync.Once
	file_protoschemas_mymessage_proto_rawDescData = file_protoschemas_mymessage_proto_rawDesc
)

func file_protoschemas_mymessage_proto_rawDescGZIP() []byte {
	file_protoschemas_mymessage_proto_rawDescOnce.Do(func() {
		file_protoschemas_mymessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoschemas_mymessage_proto_rawDescData)
	})
	return file_protoschemas_mymessage_proto_rawDescData
}

var file_protoschemas_mymessage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protoschemas_mymessage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protoschemas_mymessage_proto_goTypes = []any{
	(MessageKind)(0),         // 0: mymessage.MessageKind
	(Role)(0),                // 1: mymessage.Role
	(Result)(0),              // 2: mymessage.Result
	(*EmptyBody)(nil),        // 3: mymessage.EmptyBody
	(*SysInfo)(nil),          // 4: mymessage.SysInfo
	(*Login)(nil),            // 5: mymessage.Login
	(*ClientList)(nil),       // 6: mymessage.ClientList
	(*FTHeader)(nil),         // 7: mymessage.FTHeader
	(*FileChunk)(nil),        // 8: mymessage.FileChunk
	(*Message)(nil),          // 9: mymessage.Message
	(*ClientList_Entry)(nil), // 10: mymessage.ClientList.Entry
}
var file_protoschemas_mymessage_proto_depIdxs = []int32{
	1,  // 0: mymessage.Login.role:type_name -> mymessage.Role
	4,  // 1: mymessage.Login.info:type_name -> mymessage.SysInfo
	10, // 2: mymessage.ClientList.entries:type_name -> mymessage.ClientList.Entry
	0,  // 3: mymessage.Message.kind:type_name -> mymessage.MessageKind
	3,  // 4: mymessage.Message.empty:type_name -> mymessage.EmptyBody
	5,  // 5: mymessage.Message.login:type_name -> mymessage.Login
	6,  // 6: mymessage.Message.clients:type_name -> mymessage.ClientList
	2,  // 7: mymessage.Message.res:type_name -> mymessage.Result
	7,  // 8: mymessage.Message.ftheader:type_name -> mymessage.FTHeader
	8,  // 9: mymessage.Message.fileChunk:type_name -> mymessage.FileChunk
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protoschemas_mymessage_proto_init() }
func file_protoschemas_mymessage_proto_init() {
	if File_protoschemas_mymessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoschemas_mymessage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmptyBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoschemas_mymessage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SysInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoschemas_mymessage_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoschemas_mymessage_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ClientList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoschemas_mymessage_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FTHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoschemas_mymessage_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FileChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoschemas_mymessage_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoschemas_mymessage_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ClientList_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protoschemas_mymessage_proto_msgTypes[2].OneofWrappers = []any{}
	file_protoschemas_mymessage_proto_msgTypes[6].OneofWrappers = []any{
		(*Message_Empty)(nil),
		(*Message_Login)(nil),
		(*Message_Clients)(nil),
		(*Message_TextContent)(nil),
		(*Message_Res)(nil),
		(*Message_Ftheader)(nil),
		(*Message_FileChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoschemas_mymessage_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoschemas_mymessage_proto_goTypes,
		DependencyIndexes: file_protoschemas_mymessage_proto_depIdxs,
		EnumInfos:         file_protoschemas_mymessage_proto_enumTypes,
		MessageInfos:      file_protoschemas_mymessage_proto_msgTypes,
	}.Build()
	File_protoschemas_mymessage_proto = out.File
	file_protoschemas_mymessage_proto_rawDesc = nil
	file_protoschemas_mymessage_proto_goTypes = nil
	file_protoschemas_mymessage_proto_depIdxs = nil
}
